export const BUSINESS_BLUEPRINTS = [
	{
		id: "restaurant",
		title: "Restaurant",
		icon: "🍽️",
		prompt: `Build a modern premium restaurant website with hero, menu, reservations, chef specials, gallery, reviews, online ordering, locations, hours, contact, SEO and luxury dining aesthetic. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "hotel",
		title: "Hotel",
		icon: "🏨",
		prompt: `Build a modern premium hotel website with room listings, booking, amenities, gallery, nearby attractions, testimonials, maps, contact and premium hospitality branding. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "bakery",
		title: "Bakery",
		icon: "🥐",
		prompt: `Build a modern premium bakery website with featured products, daily specials, custom cake ordering, gallery, story, reviews, WhatsApp ordering and warm premium branding. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "cafe",
		title: "Cafe",
		icon: "☕",
		prompt: `Build a modern premium cafe website with menu, reservations, coffee story, events, gallery, loyalty program and cozy modern aesthetic. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "fast-food",
		title: "Fast Food",
		icon: "🍔",
		prompt: `Build a modern premium fast food website with combo menu, online ordering, delivery, offers, locations and bold conversion-focused layout. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "salon",
		title: "Salon & Spa",
		icon: "💇",
		prompt: `Build a modern premium luxury salon website with services, pricing, booking, team, gallery, testimonials, Instagram and elegant branding. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "barbershop",
		title: "Barbershop",
		icon: "💈",
		prompt: `Build a modern premium modern barbershop website with services, booking, barbers, gallery, reviews and contact. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "clinic",
		title: "Clinic",
		icon: "🏥",
		prompt: `Build a modern premium medical clinic website with doctors, departments, appointments, insurance, testimonials, FAQs and professional trust-first design. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "hospital",
		title: "Hospital",
		icon: "🏩",
		prompt: `Build a modern premium hospital website with specialties, emergency info, appointments, doctors, patient portal sections and accessibility. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "pharmacy",
		title: "Pharmacy",
		icon: "💊",
		prompt: `Build a modern premium pharmacy website with medicine categories, prescription refill requests, consultations and store locator. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "law",
		title: "Law Firm",
		icon: "⚖️",
		prompt: `Build a modern premium law firm website with practice areas, attorney profiles, consultation booking, case studies and trust-focused design. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "accounting",
		title: "Accounting Firm",
		icon: "📊",
		prompt: `Build a modern premium accounting website with tax services, bookkeeping, pricing, testimonials and consultation. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "real-estate",
		title: "Real Estate",
		icon: "🏘️",
		prompt: `Build a modern premium real estate website with property listings, search, agents, virtual tours, mortgage CTA and inquiries. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "construction",
		title: "Construction",
		icon: "🏗️",
		prompt: `Build a modern premium construction company website with services, projects, certifications, testimonials and quotation requests. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "architecture",
		title: "Architecture",
		icon: "📐",
		prompt: `Build a modern premium architecture portfolio with projects, process, team and inquiry forms. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "logistics",
		title: "Logistics",
		icon: "🚚",
		prompt: `Build a modern premium logistics website with shipment services, tracking placeholder, industries served and quote requests. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "travel",
		title: "Travel Agency",
		icon: "✈️",
		prompt: `Build a modern premium travel website with destinations, packages, booking inquiry, reviews and galleries. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "school",
		title: "School",
		icon: "🎓",
		prompt: `Build a modern premium school website with admissions, academics, faculty, events, gallery and contact. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "university",
		title: "University",
		icon: "🏫",
		prompt: `Build a modern premium university website with faculties, admissions, research, news and student life. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "portfolio",
		title: "Portfolio",
		icon: "🎨",
		prompt: `Build a modern premium creative portfolio with projects, skills, resume, testimonials, blog and contact. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "photography",
		title: "Photography",
		icon: "📷",
		prompt: `Build a modern premium photography website with galleries, packages, booking and client testimonials. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "agency",
		title: "Marketing Agency",
		icon: "📣",
		prompt: `Build a modern premium marketing agency website with services, case studies, pricing, testimonials and lead generation. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "software",
		title: "SaaS Startup",
		icon: "🚀",
		prompt: `Build a modern premium SaaS landing page with features, pricing, integrations, testimonials, FAQ and CTA. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "fintech",
		title: "FinTech",
		icon: "💳",
		prompt: `Build a modern premium fintech website with product overview, security, pricing, FAQs and onboarding. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "church",
		title: "Church",
		icon: "⛪",
		prompt: `Build a modern premium church website with ministries, sermons, events, donations, gallery and contact. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "ngo",
		title: "NGO",
		icon: "🤝",
		prompt: `Build a modern premium NGO website with mission, impact stories, donations, volunteering and transparency. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "gym",
		title: "Gym",
		icon: "💪",
		prompt: `Build a modern premium gym website with memberships, trainers, schedules, transformations and signup. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "fashion",
		title: "Fashion Store",
		icon: "👗",
		prompt: `Build a modern premium fashion ecommerce with collections, lookbook, cart, promotions and checkout. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "electronics",
		title: "Electronics Store",
		icon: "💻",
		prompt: `Build a modern premium electronics ecommerce with categories, featured products, warranty and support. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "supermarket",
		title: "Supermarket",
		icon: "🛒",
		prompt: `Build a modern premium supermarket website with departments, weekly deals, delivery and loyalty. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "car-dealer",
		title: "Car Dealership",
		icon: "🚗",
		prompt: `Build a modern premium car dealership with inventory, financing, trade-ins and test drive booking. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "insurance",
		title: "Insurance",
		icon: "🛡️",
		prompt: `Build a modern premium insurance website with products, quote forms, claims info and FAQs. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "bank",
		title: "Bank",
		icon: "🏦",
		prompt: `Build a modern premium bank website with personal/business banking, loans, cards and security. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "dentist",
		title: "Dental Clinic",
		icon: "🦷",
		prompt: `Build a modern premium dental website with treatments, dentists, booking and patient reviews. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "optical",
		title: "Optical",
		icon: "👓",
		prompt: `Build a modern premium optical clinic with eye exams, products, appointments and FAQs. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "pet",
		title: "Pet Store",
		icon: "🐶",
		prompt: `Build a modern premium pet store with products, grooming, adoption and booking. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "veterinary",
		title: "Veterinary Clinic",
		icon: "🐾",
		prompt: `Build a modern premium veterinary website with services, appointments, emergency contacts and pet care. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "beauty",
		title: "Cosmetics Brand",
		icon: "💄",
		prompt: `Build a modern premium beauty brand ecommerce with collections, ingredients, reviews and influencer section. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "jewelry",
		title: "Jewelry Store",
		icon: "💎",
		prompt: `Build a modern premium luxury jewelry ecommerce with collections, craftsmanship, appointments and gift guide. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "furniture",
		title: "Furniture Store",
		icon: "🛋️",
		prompt: `Build a modern premium furniture showroom with categories, room inspiration and delivery. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "developer",
		title: "Developer Portfolio",
		icon: "👨‍💻",
		prompt: `Build a modern premium developer portfolio with projects, GitHub, skills, resume and contact. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "music",
		title: "Music Studio",
		icon: "🎵",
		prompt: `Build a modern premium music studio with services, portfolio, bookings and testimonials. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "event",
		title: "Event Planner",
		icon: "🎉",
		prompt: `Build a modern premium event planning website with services, packages, gallery and inquiry. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "wedding",
		title: "Wedding Planner",
		icon: "💍",
		prompt: `Build a modern premium wedding planning site with packages, galleries, testimonials and booking. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "cleaning",
		title: "Cleaning Service",
		icon: "🧹",
		prompt: `Build a modern premium cleaning company with residential/commercial services and quotes. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "security",
		title: "Security Company",
		icon: "🚨",
		prompt: `Build a modern premium security services with offerings, industries, certifications and consultations. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "manufacturing",
		title: "Manufacturing",
		icon: "🏭",
		prompt: `Build a modern premium manufacturer website with products, capabilities, industries and RFQ. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "mining",
		title: "Mining",
		icon: "⛏️",
		prompt: `Build a modern premium mining corporate site with operations, ESG, investors and careers. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "agriculture",
		title: "Agriculture",
		icon: "🌾",
		prompt: `Build a modern premium agribusiness site with products, sustainability and distributors. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "bookstore",
		title: "Bookstore",
		icon: "📚",
		prompt: `Build a modern premium bookstore ecommerce with genres, recommendations and events. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "coaching",
		title: "Business Coach",
		icon: "🧠",
		prompt: `Build a modern premium coach website with programs, testimonials, booking and resources. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "linkbio",
		title: "Link in Bio",
		icon: "🔗",
		prompt: `Build a modern premium personal link hub with social links, featured content, newsletter and contact. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
	{
		id: "nonprofit",
		title: "Foundation",
		icon: "❤️",
		prompt: `Build a modern premium foundation website with initiatives, donations, reports and partners. The website should include a compelling hero section, clear navigation, about section, services or products where appropriate, strong calls-to-action, testimonials, FAQ, contact page, WhatsApp integration, SEO-friendly structure, responsive mobile-first layout, fast loading performance, accessible design, elegant typography, subtle animations, and a luxury dark aesthetic suitable for this business.`,
	},
];
