// app/api/st/t-a/download/route.ts

import JSZip from "jszip";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function POST(request: Request) {
	try {
		const supabase = await createClient();
		const {
			data: { user },
		} = await supabase.auth.getUser();

		if (!user) {
			return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
		}

		const body = await request.json();

		// ─── Validation ──────────────────────────────────────────────────
		if (!body.type || !body.id) {
			return NextResponse.json(
				{ error: "Type and ID are required" },
				{ status: 400 },
			);
		}

		if (!["template", "animation"].includes(body.type)) {
			return NextResponse.json(
				{ error: 'Invalid type. Must be "template" or "animation"' },
				{ status: 400 },
			);
		}

		const format = body.format || "html";

		// ─── Handle Template Download ──────────────────────────────────
		if (body.type === "template") {
			const { data: template, error } = await supabase
				.from("ta_templates")
				.select("*")
				.eq("id", body.id)
				.single();

			if (error || !template) {
				return NextResponse.json(
					{ error: "Template not found" },
					{ status: 404 },
				);
			}

			// Check access: owner OR public template
			if (template.user_id !== user.id && !template.is_public) {
				return NextResponse.json({ error: "Access denied" }, { status: 403 });
			}

			// ─── Increment download count ────────────────────────────────
			await supabase.rpc("increment_template_downloads", {
				template_id: body.id,
			});

			// ─── Log download ─────────────────────────────────────────────
			await supabase.from("ta_downloads").insert({
				user_id: user.id,
				template_id: body.id,
				format: format,
				downloaded_at: new Date().toISOString(),
			});

			// ─── HTML Format ──────────────────────────────────────────────
			if (format === "html") {
				const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${sanitizeString(template.name)}</title>
  <style>${template.css_code || ""}</style>
</head>
<body>
  ${template.html_code || ""}
  <script>${template.js_code || ""}</script>
</body>
</html>`;

				return new NextResponse(html, {
					status: 200,
					headers: {
						"Content-Type": "text/html; charset=utf-8",
						"Content-Disposition": `attachment; filename="${sanitizeFilename(template.name)}.html"`,
						"Cache-Control": "private, no-cache, no-store, must-revalidate",
					},
				});
			}

			// ─── ZIP Format ──────────────────────────────────────────────────
			if (format === "zip") {
				const zip = new JSZip();

				const fileName = sanitizeFilename(template.name);

				zip.file(
					"index.html",
					`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${sanitizeString(template.name)}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  ${template.html_code || ""}
  <script src="script.js"></script>
</body>
</html>`,
				);

				zip.file("style.css", template.css_code || "");
				zip.file("script.js", template.js_code || "");

				// ─── Readme ──────────────────────────────────────────────────
				const readmeContent = `# ${template.name}

${template.description || "Template exported from Prime Boostage | Elite Home"}

## Export Information
- **Exported:** ${new Date().toISOString()}
- **Category:** ${template.category}
- **Type:** ${template.type}

## Files
- \`index.html\` - Main HTML file
- \`style.css\` - All styles
- \`script.js\` - JavaScript functionality

## Usage
Open \`index.html\` in your browser to view the template.

---
Generated by Prime Boostage | Elite Home
`;

				zip.file("README.md", readmeContent);

				// ─── FIX: Convert Buffer to Uint8Array for Response ──────────────
				const zipBuffer = await zip.generateAsync({
					type: "nodebuffer",
					compression: "DEFLATE",
					compressionOptions: { level: 6 },
				});

				// Convert to Uint8Array to satisfy BodyInit type
				const zipData = new Uint8Array(zipBuffer);

				return new Response(zipData, {
					status: 200,
					headers: {
						"Content-Type": "application/zip",
						"Content-Disposition": `attachment; filename="${fileName}.zip"`,
						"Content-Length": String(zipData.length),
						"Cache-Control": "private, no-cache, no-store, must-revalidate",
					},
				});
			}
			// ─── JSON Format ──────────────────────────────────────────────
			if (format === "json") {
				const jsonData = {
					...template,
					exported_at: new Date().toISOString(),
					exporter: {
						id: user.id,
						platform: "Prime Boostage | Elite Home",
					},
				};

				const jsonString = JSON.stringify(jsonData, null, 2);

				return new NextResponse(jsonString, {
					status: 200,
					headers: {
						"Content-Type": "application/json; charset=utf-8",
						"Content-Disposition": `attachment; filename="${sanitizeFilename(template.name)}.json"`,
						"Cache-Control": "private, no-cache, no-store, must-revalidate",
					},
				});
			}

			return NextResponse.json(
				{ error: "Unsupported format. Supported: html, zip, json" },
				{ status: 400 },
			);
		}

		// ─── Handle Animation Download ──────────────────────────────────
		if (body.type === "animation") {
			const { data: animation, error } = await supabase
				.from("ta_animations")
				.select("*")
				.eq("id", body.id)
				.single();

			if (error || !animation) {
				return NextResponse.json(
					{ error: "Animation not found" },
					{ status: 404 },
				);
			}

			if (animation.user_id !== user.id) {
				return NextResponse.json({ error: "Access denied" }, { status: 403 });
			}

			// ─── Increment download count ────────────────────────────────
			await supabase.rpc("increment_animation_downloads", {
				animation_id: body.id,
			});

			// ─── Log download ─────────────────────────────────────────────
			await supabase.from("ta_downloads").insert({
				user_id: user.id,
				animation_id: body.id,
				format: format,
				downloaded_at: new Date().toISOString(),
			});

			// ─── CSS Format ──────────────────────────────────────────────
			if (format === "css") {
				let css = animation.css_code || "";

				// ─── Generate CSS from keyframes if no css_code ────────────
				if (!css && animation.keyframes) {
					const keyframeName = sanitizeKeyframeName(animation.name);
					const keyframeStyles = Object.entries(animation.keyframes)
						.map(([key, value]) => {
							const props = Object.entries(value as Record<string, string>)
								.map(([prop, val]) => `${prop}: ${val};`)
								.join(" ");
							return `  ${key} { ${props} }`;
						})
						.join("\n");

					css = `/* Animation: ${animation.name} */
/* Exported from Prime Boostage | Elite Home */

@keyframes ${keyframeName} {
${keyframeStyles}
}

.animated-${keyframeName} {
  animation: ${keyframeName} ${animation.duration}ms ${animation.easing} ${animation.delay}ms;
  animation-fill-mode: ${animation.fill_mode || "forwards"};
  animation-iteration-count: ${animation.iteration_count || "1"};
  animation-direction: ${animation.direction || "normal"};
  animation-timing-function: ${animation.easing};
}

/* Trigger: ${animation.trigger || "load"} */
/* Duration: ${animation.duration}ms */
/* Delay: ${animation.delay}ms */
`;
				}

				return new NextResponse(css, {
					status: 200,
					headers: {
						"Content-Type": "text/css; charset=utf-8",
						"Content-Disposition": `attachment; filename="${sanitizeFilename(animation.name)}.css"`,
						"Cache-Control": "private, no-cache, no-store, must-revalidate",
					},
				});
			}

			// ─── JSON Format ──────────────────────────────────────────────
			if (format === "json") {
				const jsonData = {
					...animation,
					exported_at: new Date().toISOString(),
					exporter: {
						id: user.id,
						platform: "Prime Boostage | Elite Home",
					},
				};

				const jsonString = JSON.stringify(jsonData, null, 2);

				return new NextResponse(jsonString, {
					status: 200,
					headers: {
						"Content-Type": "application/json; charset=utf-8",
						"Content-Disposition": `attachment; filename="${sanitizeFilename(animation.name)}.json"`,
						"Cache-Control": "private, no-cache, no-store, must-revalidate",
					},
				});
			}

			return NextResponse.json(
				{ error: "Unsupported format. Supported: css, json" },
				{ status: 400 },
			);
		}

		return NextResponse.json({ error: "Invalid request" }, { status: 400 });
	} catch (error: any) {
		console.error("Download error:", error);
		return NextResponse.json(
			{ error: error.message || "Internal server error" },
			{ status: 500 },
		);
	}
}

// ─── Helper Functions ────────────────────────────────────────────────

/**
 * Sanitize a string for safe HTML output
 */
function sanitizeString(str: string): string {
	if (!str) return "";
	return str
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;")
		.replace(/'/g, "&#039;");
}

/**
 * Sanitize a filename for safe download
 */
function sanitizeFilename(name: string): string {
	if (!name) return "download";
	return name
		.toLowerCase()
		.replace(/[^a-z0-9\s-]/g, "") // Remove special characters
		.replace(/\s+/g, "-") // Replace spaces with hyphens
		.replace(/-+/g, "-") // Remove duplicate hyphens
		.trim();
}

/**
 * Sanitize a keyframe name for CSS
 */
function sanitizeKeyframeName(name: string): string {
	if (!name) return "animation";
	return (
		name
			.toLowerCase()
			.replace(/[^a-z0-9-]/g, "-")
			.replace(/-+/g, "-")
			.replace(/^-|-$/g, "")
			.trim() || "animation"
	);
}
